backend:
  name: git-gateway
  branch: master
media_folder: "images/uploads"

collection:
  - name: "friends"
    label: "Friend"
    folder: "_friends"
    create: true
    fields:
      - {label: "Name", name: "name" , widget: "string"}
      - {label: "Location", name: "location" , widget: "string"}